# Generated by Django 3.2 on 2022-02-23 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20220223_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='description',
            new_name='details',
        ),
    ]
