# Generated by Django 3.2 on 2022-02-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_rename_description_tickets_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='details',
            field=models.TextField(default=False, max_length=500),
        ),
    ]
