# Generated by Django 3.2 on 2022-02-23 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_alter_tickets_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='details',
            new_name='specify',
        ),
    ]
