# Generated by Django 3.2 on 2022-02-23 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_rename_details_tickets_specify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='specify',
        ),
    ]
