# Generated by Django 3.2 on 2022-02-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_remove_tickets_specify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='ticket_priority',
            field=models.CharField(blank=True, choices=[('fast', 'urgent'), ('medium ', 'medium'), ('delay ', 'low')], max_length=50, null=True),
        ),
    ]
