# Generated by Django 3.2 on 2022-02-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_alter_tickets_ticket_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='ticket_priority',
            field=models.CharField(blank=True, choices=[('fast', 'High'), ('medium ', 'Medium'), ('delay ', 'Low')], max_length=50, null=True),
        ),
    ]
