# Generated by Django 4.0.3 on 2022-04-07 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_alter_tickets_ticket_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='ticket_status',
        ),
    ]
