# Generated by Django 3.2 on 2022-05-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_remove_tickets_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='ticket_priority',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
